SELECT * FROM properties WHERE workspace_id=@workspace AND id=@property AND archived=0;
SELECT u.*,l.block_id,l.floor FROM property_units u LEFT JOIN community_unit_locations l ON l.workspace_id=u.workspace_id AND l.unit_id=u.id WHERE u.workspace_id=@workspace AND u.property_id=@property ORDER BY u.label;
SELECT * FROM community_parties WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_ownerships WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_agreements WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT c.*,COALESCE((SELECT SUM(p.amount) FROM community_payments p WHERE p.workspace_id=c.workspace_id AND p.charge_id=c.id AND p.status='verified'),0) AS verified_paid FROM community_charges c WHERE c.workspace_id=@workspace AND c.property_id=@property;
SELECT * FROM community_payments WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_expenses WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_sellers WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_products WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_orders WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_groups WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_pledges WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_gate_entries WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_facilities WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_bookings WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_notes WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_layouts WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_audit WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_receipts WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT agreement_id,unit_id FROM community_agreement_units WHERE workspace_id=@workspace AND property_id=@property;
SELECT expense_id,party_id,amount FROM community_expense_allocations WHERE workspace_id=@workspace AND property_id=@property;
SELECT * FROM community_services WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_service_requests WHERE workspace_id=@workspace AND property_id=@property ORDER BY created_at,id;
SELECT * FROM community_blocks WHERE workspace_id=@workspace AND property_id=@property ORDER BY name;
SELECT * FROM community_block_layouts WHERE workspace_id=@workspace AND property_id=@property ORDER BY block_id,floor;
SELECT d.*,COALESCE(NULLIF(u.display_name,''),'Community member') AS recipient_name FROM community_deliveries d LEFT JOIN users u ON u.workspace_id=d.workspace_id AND u.user_id=d.user_id WHERE d.workspace_id=@workspace AND d.property_id=@property ORDER BY d.created_at,d.id;
